<?xml version="1.0" encoding="utf-8"?>
<Database Name="AnotherBlog" ContextNamespace="TheOffWing.AnotherBlog.Core.Entity" Class="BlogDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=AnotherBlog;Integrated Security=True;Pooling=False" SettingsObjectName="TheOffWing.AnotherBlog.Core.Properties.Settings" SettingsPropertyName="AnotherBlogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DbInfo" Member="DbInfos">
    <Type Name="DbInfo">
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_BlogUser" Member="BlogUsers" ThisKey="RoleId" OtherKey="RoleId" Type="BlogUser" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tag_BlogEntryTag" Member="BlogEntryTags" ThisKey="id" OtherKey="TagId" Type="BlogEntryTag" />
      <Association Name="Blog_Tag" Member="Blog" ThisKey="BlogId" OtherKey="BlogId" Type="Blog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogEntryTags" Member="BlogEntryTags">
    <Type Name="BlogEntryTag">
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BlogEntryId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tag_BlogEntryTag" Member="Tag" ThisKey="TagId" OtherKey="id" Type="Tag" IsForeignKey="true" />
      <Association Name="BlogEntry_BlogEntryTag" Member="BlogEntry" ThisKey="BlogEntryId" OtherKey="EntryId" Type="BlogEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogUsers" Member="BlogUsers">
    <Type Name="BlogUser">
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_BlogUser" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="Blog_BlogUser" Member="Blog" ThisKey="BlogId" OtherKey="BlogId" Type="Blog" IsForeignKey="true" />
      <Association Name="User_BlogUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogRollLinks" Member="BlogRollLinks">
    <Type Name="BlogRollLink">
      <Column Name="LinkName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Blog_BlogRollLink" Member="Blog" ThisKey="BlogId" OtherKey="BlogId" Type="Blog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blogs" Member="Blogs">
    <Type Name="Blog">
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SubFolder" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WelcomeMessage" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContactEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Blog_Tag" Member="Tags" ThisKey="BlogId" OtherKey="BlogId" Type="Tag" />
      <Association Name="Blog_BlogUser" Member="BlogUsers" ThisKey="BlogId" OtherKey="BlogId" Type="BlogUser" />
      <Association Name="Blog_BlogRollLink" Member="BlogRollLinks" ThisKey="BlogId" OtherKey="BlogId" Type="BlogRollLink" />
      <Association Name="Blog_BlogEntry" Member="BlogEntries" ThisKey="BlogId" OtherKey="BlogId" Type="BlogEntry" />
      <Association Name="Blog_EntryComment" Member="EntryComments" ThisKey="BlogId" OtherKey="BlogId" Type="EntryComment" />
    </Type>
  </Table>
  <Table Name="dbo.SiteInfo" Member="SiteInfos">
    <Type Name="SiteInfo">
      <Column Name="About" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BlogEntries" Member="BlogEntries">
    <Type Name="BlogEntry">
      <Column Name="EntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntryText" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DatePosted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="BlogEntry_BlogEntryTag" Member="BlogEntryTags" ThisKey="EntryId" OtherKey="BlogEntryId" Type="BlogEntryTag" />
      <Association Name="BlogEntry_EntryComment" Member="EntryComments" ThisKey="BlogId" OtherKey="BlogId" Type="EntryComment" />
      <Association Name="Blog_BlogEntry" Member="Blog" ThisKey="BlogId" OtherKey="BlogId" Type="Blog" IsForeignKey="true" />
      <Association Name="User_BlogEntry" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedCommenter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSiteAdministrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="User_BlogUser" Member="BlogUsers" ThisKey="UserId" OtherKey="UserId" Type="BlogUser" />
      <Association Name="User_BlogEntry" Member="BlogEntries" ThisKey="UserId" OtherKey="UserId" Type="BlogEntry" />
    </Type>
  </Table>
  <Table Name="dbo.EntryComments" Member="EntryComments">
    <Type Name="EntryComment">
      <Column Name="CommentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthorEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelatedComment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AuthorName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DatePosted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BlogEntry_EntryComment" Member="BlogEntry" ThisKey="BlogId" OtherKey="BlogId" Type="BlogEntry" IsForeignKey="true" />
      <Association Name="Blog_EntryComment" Member="Blog" ThisKey="BlogId" OtherKey="BlogId" Type="Blog" IsForeignKey="true" />
    </Type>
  </Table>
</Database>